server:
  port: 80

#mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    MySQL连接配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: root
    password: 2003

#    如果需要其他数据库，就自己进行配置

  jackson:
#    指定日期格式化时区
    time-zone: GMT+8
#    指定日期格式
    data-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/


mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml

pagehelper:
  reasonable: true,
  support-methods-arguments: true,
  params: count=countSql

#指定数据库
starts:
  database: mysql

